### ISSUE TITLE
Add Export as .py

### ISSUE THREAD

**Issue by zackmark29** [Svenskithesource/pySpy#7]
Is it possible to export the decompiled pyc to py?
Thank you.

**Comment by Svenskithesource** [comment]
It's definitely possible, but all the decompilers for Python 3.8+ aren't stable enough. Also, remember there is even less chance that they'll work if you manually edit the bytecode.

**Comment by zackmark29** [comment]
> It's definitely possible, but all the decompilers for Python 3.8+ aren't stable enough. Also, remember there is even less chance that they'll work if you manually edit the bytecode.

Yes, you're right. I guess this is enough for now since this is really helpful already.
